id: P006823
initial_creation_type: ocr
created_at: 26/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1KG8828
  title: རྟགས་རིགས་དང་ཕྱོགས་སྒྲའི་རྩོད་ལན་དང་ལུང་འགལ་ཕྱོགས་ཆོས་འཁོར་ལོའི་རེའུ་མིག་གཞན་སྟོང་བགྲོ་གླེང་ཐེངས་གསུམ་པའི་དྲིས་ལན།
  author: ''
  volumes:
    feacaa809faf4b59ba6e7b0f76c324b5:
      image_group_id: I1KG8832
      title: ''
      volume_number: 1
      total_pages: 264
      base_file: v001.txt
