id: opecha:P006823
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG8828
  title: རྟགས་རིགས་དང་ཕྱོགས་སྒྲའི་རྩོད་ལན་དང་ལུང་འགལ་ཕྱོགས་ཆོས་འཁོར་ལོའི་རེའུ་མིག་གཞན་སྟོང་བགྲོ་གླེང་ཐེངས་གསུམ་པའི་དྲིས་ལན།
  volume: ''
  author: ''
